### PR TITLE
Boilerplate webpage

### PR DESCRIPTION
**Pull request by MakisH**
First skeleton for the webpage, copying from https://de-rse.org/chapter/ ([code](https://github.com/DE-RSE/chapter)), which is based on https://github.com/mmistakes/minimal-mistakes.

This should eventually appear under https://de-rse.org/teach-and-learn/.

I already took the liberty to add the de-RSE branding, as I assume we are building this to be an official de-RSE page. The author currently appears as the de-RSE Vorstand, same as in the chapter.

Before marking this as "Ready to review", I still want to:

- [x] Synchronize with the latest changes from the upstream theme
- [x] Update the images and other visual elements
- [x] Update the Makefile
- [x] Remove any potentially unneeded files and add a more extensive gitignore

~~In a follow-up PR, I will add~~ This already includes a mechanism for collecting resources into a database and rendering from it, based on how we do this in the [preCICE literature guide](https://precice.org/fundamentals-literature-guide.html).

Current rendering:

Screenshot 2024-02-15 at 17-04-26 Learning and teaching RSE

____

Screenshot 2024-02-15 at 17-21-48 Learn research software engineering

____

Screenshot 2024-02-15 at 17-21-57 Teach research software engineering

____

Screenshot 2024-02-15 at 17-22-04 RSE Competencies

### CODE REVIEW

**Comment by MakisH** [comment]
I updated the address, the pictures, and some consistency things (see screenshot in the first comment). I also added a first entry for the resources database, even though the system does not work yet (content is not sourced). This should be easy to fix, I just don't have time till next week.

cc @CaptainSifff

**Comment by CaptainSifff** [comment]
Hi!
this looks already pretty fine! I can't check how it is currently rendered, but I think since you already have the basic menu structure this should enable us a start onto which we can attach our ideas. We can sure wait, until you have fixed the database issues.

**Comment by MakisH** [comment]
@CaptainSifff @jngrad this is now ready to merge from my side.

We still need to add summaries for the different competencies, but I would consider that a different work package.

The image you see is optional and fetched from the website of the respective resource. I only use it as an example to showcase that we can also include images. We of course can improve the layout, but I would again consider that a separate work package.

After we merge this, I will port all the material from #2 and continue working on it, so let's please not keep it open for too long.

**Review by jngrad — APPROVED** [review]
The proposed website structure looks good to me. I think the suggestion of deferring the other tasks in the TODO list to dedicated PRs makes sense, as it would allow multiple people to work on them in parallel, instead of working in an ever-growing PR that mixes content creation and coding.

I'm not familiar with Ruby, so I cannot meaningfully comment on the Jekyll pipeline. The templating is done with Liquid, whose syntax is quite transparent to Jinja users, thus editing the dynamic parts of the HTML files should be relatively accessible to contributors who know Ruby or Python. I downloaded the generated website files from the GitHub Actions, and after converting all internal links from PHP paths to relative paths, I was able to browse the pages locally.

**Comment by MakisH** [comment]
> I downloaded the generated website files from the GitHub Actions, and after converting all internal links from PHP paths to relative paths, I was able to browse the pages locally.

What exactly did you do?

> The templating is done with Liquid, whose syntax is quite transparent to Jinja users, thus editing the dynamic parts of the HTML files should be relatively accessible to contributors who know Ruby or Python.

I was not very happy that I had to repeat a lot of code, e.g., in the `competencies.md`. Is there an easy way to make a function in Liquid or some other layer?

**Comment by jngrad** [comment]
> > I downloaded the generated website files from the GitHub Actions, and after converting all internal links from PHP paths to relative paths, I was able to browse the pages locally.
> 
> What exactly did you do?

I changed links to internal pages from `href="/learn-and-teach/teach/"` to `href="teach/index.html"`, and links to CSS style sheets from `href="/learn-and-teach/assets/css/main.css"` to `href="../assets/css/main.css"`.

> > The templating is done with Liquid, whose syntax is quite transparent to Jinja users, thus editing the dynamic parts of the HTML files should be relatively accessible to contributors who know Ruby or Python.
> 
> I was not very happy that I had to repeat a lot of code, e.g., in the `competencies.md`. Is there an easy way to make a function in Liquid or some other layer?

Would the trick outlined in [reggi/shopify-liquid-functions](https://github.com/reggi/shopify-liquid-functions) work for you? I have never used Liquid and had to do a little bit of research, but if I understood it correctly, the body of the function is written to a file and the function is "called" by including the file.

**Comment by CaptainSifff** [comment]
Great!

**Review by CaptainSifff — APPROVED** [review]

**Comment by MakisH** [comment]
> > I was not very happy that I had to repeat a lot of code, e.g., in the `competencies.md`. Is there an easy way to make a function in Liquid or some other layer?
> 
> Would the trick outlined in [reggi/shopify-liquid-functions](https://github.com/reggi/shopify-liquid-functions) work for you? I have never used Liquid and had to do a little bit of research, but if I understood it correctly, the body of the function is written to a file and the function is "called" by including the file.

Thank you, I will deal with this in a separate PR.

**Pull request merged**
